name: FoliaStuff
version: '1.1'
main: 'me.paul.CasesStandalone'
description: Wheel, Cases, Goated on the Sticks
folia-supported: true
load: POSTWORLD

api-version: '1.20'
bootstrapper: me.paul.foliastuff.other.FoliaBootstrapper
depend: [PlaceholderAPI]

authors:
  - paulyg

commands:
  spawn:
    description: TP to spawn
  home:
    description: TP to home
  sethome:
    description: Set home
  displayname:
    description: Change display name
    aliases: [dn]
  case:
    description: open a case smiley
    op: true
